window._CCSettings = {
    platform: "wechatgame",
    groupList: [
        "default",
        "role",
        "buffer",
        "road",
        "enemy",
        "enemy_bullet",
        "role_bullet",
        "ui",
        "end",
        "bg",
        "trap"
    ],
    collisionMatrix: [
        [
            false,
            false,
            null,
            null,
            null,
            null,
            false
        ],
        [
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            null,
            true,
            null,
            true
        ],
        [
            false,
            true,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            true,
            false,
            false,
            true,
            true,
            true
        ],
        [
            false,
            true,
            false,
            true,
            true,
            false,
            true
        ],
        [
            false,
            true,
            false,
            true,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            true,
            true,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        [
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ]
    ],
    hasResourcesBundle: true,
    hasStartSceneBundle: false,
    remoteBundles: [],
    subpackages: [
        "ad",
        "endform",
        "gameform",
        "homeform",
        "mistouch",
        "shopform",
        "tryform"
    ],
    launchScene: "db://assets/scene/Loading.fire",
    orientation: "portrait",
    server: "",
    debug: true,
    jsList: [
        "assets/moosnowSdk/moosnow.conf.js",
        "assets/moosnowSdk/moosnow.platform.sdk.js"
    ]
};
